# fly.toml app configuration file generated for ascii-movie on 2025-05-31T16:52:55Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ascii-movie'
primary_region = 'bos'

[build]

[[services]]
  protocol = 'tcp'
  internal_port = 3333
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 23
    handlers = []

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
